// <auto-generated />
namespace OneOff.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class SoftDeleteProperty : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SoftDeleteProperty));
        
        string IMigrationMetadata.Id
        {
            get { return "201801040416070_SoftDeleteProperty"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
